name: Fetch all pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch and save
        env:
          WIKI_API_URL: https://youtube.fandom.com/api.php
        run: |
          ALL_PAGES=""
          CONTINUE=""
          ATTEMPTS=0

          while [[ -n "$CONTINUE" || -z "$ALL_PAGES" ]]; do
            ATTEMPTS=$((ATTEMPTS + 1))
            echo "Fetching pages - Attempt $ATTEMPTS"

            RESPONSE=$(curl -s "$WIKI_API_URL" \
                -d "action=query" \
                -d "list=allpages" \
                -d "aplimit=max" \
                -d "apcontinue=$CONTINUE" \
                -d "maxlag=5" \
                -d "format=json")
            
            if [[ "$(echo "$RESPONSE" | jq -r '.error?.code')" == "maxlag" ]]; then
              echo "API is lagging. Retrying in 3 seconds..."
              sleep 3
              continue
            fi

            ALL_PAGES+="$(echo "$RESPONSE" | jq -r '.query.allpages[].title')\n"
            CONTINUE=$(echo "$RESPONSE" | jq -r '.continue?.apcontinue')
          done

          echo -e "$ALL_PAGES" > allpages.txt

          echo "All pages fetched and saved to 'allpages.txt'."

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add pages.txt
          git commit -m "Update allpages.txt"
          git push
