name: Fetch all pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch and save
        env:
          WIKI_API_URL: https://youtube.fandom.com/api.php
        run: |
          ALL_PAGES=""
          CONTINUE=""
          while [[ -n "$CONTINUE" || -z "$ALL_PAGES" ]]; do
            RESPONSE=$(curl -s "$WIKI_API_URL" \
                -d "action=query" \
                -d "list=allpages" \
                -d "aplimit=max" \
                -d "apcontinue=$CONTINUE" \
                -d "format=json")
            ALL_PAGES+="$(echo "$RESPONSE" | jq -r '.query.allpages[].title')\n"
            CONTINUE=$(echo "$RESPONSE" | jq -r '.continue?.apcontinue')
          done

          echo -e "$ALL_PAGES" > pages.txt

          echo "All pages fetched and saved to 'pages.txt'."

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add Allpages.txt
          git commit -m "Update list of pages" || echo 'No changes, skipping push...'
          git push -u origin main
