# This is a basic workflow to help you get started with Actions

name: Filter statistics

# Controls when the workflow will run
on:
  push:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  filter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Filter the statistics file
        run: |
          filtered_data=$(jq '.query.statistics | {"Total pages": .pages, "Articles": .articles, "Total edits": .edits, "Total images": .images, "Active users": .activeusers, "Administrators": .admins}' statistics.json)

      - name: Output as Markdown
        run: |
          markdown_out=$(echo "$filtered_data" | jq -r '["Total pages", "Articles", "Total edits", "Total images", "Active users", "Administrators"], (.[] | [.Pages, .Articles, .Edits, .Images, .Activeusers, .Admins]) | @tsv' | sed 's/\t/ | /g')

      # Runs a set of commands using the runners shell
      - name: Write to file and commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          echo "$markdown_out" > statistics.md
          git add statistics.md
          git commit -m "Update statistics table" || echo "Source is same as repo"
          git push
